export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const OPEN_FEED_DETAIL: 'OPEN_FEED_DETAIL' = 'OPEN_FEED_DETAIL';
export const CLOSE_FEED_DETAIL: 'CLOSE_FEED_DETAIL' = 'CLOSE_FEED_DETAIL';