export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED';
export const ORDER_OPEN: 'ORDER_OPEN' = 'ORDER_OPEN';
export const ORDER_CLOSE: 'ORDER_CLOSE' = 'ORDER_CLOSE';